package com.expanz.app;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import android.app.Activity;
import android.app.AlertDialog;
import android.app.Notification;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.database.Cursor;
import android.net.Uri;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.view.inputmethod.InputMethodManager;
import android.widget.Toast;

import com.expanz.ExpanzCommand;
import com.expanz.ServiceCallback;
import com.expanz.model.Message;
import com.expanz.model.entity.Activities;
import com.expanz.model.entity.ImageDetails;
import com.expanz.model.request.CreateActivityRequest;
import com.expanz.model.request.CreateSessionRequest;
import com.expanz.model.request.DataPublicationRequest;
import com.expanz.model.request.GetSessionDataRequest;
import com.expanz.model.response.ActivityResponse;
import com.expanz.model.response.Data;
import com.expanz.model.response.FieldResponse;
import com.expanz.model.response.ProcessAreaActivityResponse;
import com.expanz.model.response.ProcessAreaResponse;
import com.expanz.model.response.SessionResponse;
import com.expanz.util.ActivityMapping;
import com.expanz.util.ActivityMappingHolder;
import com.expanz.util.ImageCaptureAgent;
import com.expanz.webservice.ActivityHandler;
import com.expanz.widget.EditTextEx;
import com.expanz.widget.ExpanzFieldWidget;
import com.expanz.widget.ImageViewEx;
import com.expanz.widget.ListViewEx;
import com.expanz.widget.TextViewEx;

/**
 * Base class for all non list based Expanz (Android) Activities. 
 * Subclasses of this class should be generated by an IDE and should contain minimal code
 * or no code in the case where tooling support is used.
 * 
 */
public abstract class ActivityEx extends Activity implements MessageListener, ContextEx {
	
	/**
	 * Constant for camera integration activity result
	 */
	public static final int TAKE_PICTURE = 1;
	
	/**
	 * defines what type of default message display is utilized by this activity
	 */
	private int messageHandlerType = 2;
	
	/**
	 * the expanz activity associated with this android activity
	 */
	protected String activityHandle;
	
	/**
	 * the expanz session this activity belongs to
	 */
	protected String sessionHandle;
	
	/**
	 * The Activity specific data generated from tooling
	 */
	protected ActivityMapping mapping;
	
	/**
	 * Label for the field widgets, needs to be separate as same field id is used for widget and label
	 */
	private Map<String, List<TextViewEx>> fieldLabels = new HashMap<String, List<TextViewEx>>();
	
	/**
	 * Any field widget views that exists as a child of the root view for this activity
	 */
	private Map<String, List<ExpanzFieldWidget>> fieldWidgets = new HashMap<String, List<ExpanzFieldWidget>>();
	
	/**
	 * ListViews that are inside the activity's view
	 */
	private Map<String, ListViewEx> lists = new HashMap<String, ListViewEx>();
	
	/**
	 * the root view for this activity, need so we can recurse child elements
	 */
	private ViewGroup rootLayout;
	
	/**
	 * the mappings for menu items
	 */
	private List<ActivityMapping> mappings = new ArrayList<ActivityMapping>();
	
	/**
	 * Used for lookup of the xml content for the activity
	 */
	private Uri activityUri;
	
	/**
	 * store any properties between activity 
	 */
	private SharedPreferences mPrefs;
	
	
	/**
	 * Is this a newly created android activity, used so we don't recreate an 
	 * activity if the phone orientation is changed etc. 
	 */
	private boolean isNew = true;
	
	/**
	 * Fields of the activity that are media resources, e.g. images
	 */
	private List<String> mediaResourceFields = new ArrayList<String>();
	
	/**
	 * Send images to the server via camera intent.
	 */
	private ImageCaptureAgent imageCaptureAgent;
	
	/**
	 * The fields that are children of this Activity, 
	 * used for optimization
	 */
	private Set<String> includedFields = new HashSet<String>();

	
	@Override
	public void onCreate(Bundle savedInstanceState) {
		
		super.onCreate(savedInstanceState);
		
		mPrefs = getSharedPreferences("expanz", MODE_PRIVATE);
		
		sessionHandle = getIntent().getStringExtra(ExpanzConstants.SESSION_HANDLE);
		
		if(getIntent().getStringExtra(ExpanzConstants.ACTIVITY_HANDLE) != null) {
			activityHandle = getIntent().getStringExtra(ExpanzConstants.ACTIVITY_HANDLE);
		}
		
		//TODO need to invalidate when session/activity times out, i.e. isNew = true
		if(savedInstanceState != null && savedInstanceState.getBoolean(ExpanzConstants.NOT_NEW)) {
			isNew = false;
		} 

		loadMapping();

	}
	
	public Map<String, List<TextViewEx>> getFieldLabels() {
		return fieldLabels;
	}

	public Map<String, List<ExpanzFieldWidget>> getFieldWidgets() {
		return fieldWidgets;
	}
	
	public Context getContextRef() {
		return this;
	}
	
	/**
	 * Set the state of the current activity object with configuration data, from the tooling
	 */
	protected void loadMapping() {
		
		mapping = ActivityMappingHolder.getInstance().getByForm(this.getClass().getName());

		if(mapping.getContentView() != null) {
			setContentView(mapping.getContentView());
		}
		
		if(mapping.getRootLayout() != null) {
			setRootLayout(mapping.getRootLayout());
		}
		
		if(mapping.getMessageHandlerType() != null) {
			setMessageHandlerType(mapping.getMessageHandlerType());
		}
		
		createMenu();
		
		initFields(); 
		
		if(mapping.isCreateActivity()) {
			createActivity(mapping.getExpanzActivityName(), mapping.getStyle(), mapping.getPublications());
		}
		
	}
	
	/**
	 * the handle for the "expanz" activity associated with this android activity 
	 * 
	 * @return
	 */
	public String getActivityHandle() {
		return activityHandle;
	}

	public void setActivityHandle(String activityHandle) {
		this.activityHandle = activityHandle;
	}

	/**
	 * The handle of the current expanz session
	 * 
	 * @return
	 */
	public String getSessionHandle() {
		return sessionHandle;
	}

	public void setSessionHandle(String sessionHandle) {
		this.sessionHandle = sessionHandle;
	}
	
	/**
	 * Load an activity from local store, i.e. in place of creating it
	 * 
	 * @param activityName
	 */
	protected ActivityResponse loadActivity(String activityName) {
		
		ActivityResponse activity = null;
		
		String activityUriString = getIntent().getStringExtra(ExpanzConstants.TRANSITION_URI);
		
		if(activityUriString == null) {
			activityUriString = mPrefs.getString(ExpanzConstants.ACTIVITY_URI, null);
		}
		
		if(activityUriString != null) {
			
			activityUri = Uri.parse(activityUriString);
			
			Cursor cursor = managedQuery(activityUri,
					new String[] { Activities.ActivityEntity.PAYLOAD }, 
					null, null, null);
			
			if(cursor.moveToFirst()) {
				
				String payload = cursor.getString(cursor.getColumnIndex(Activities.ActivityEntity.PAYLOAD));
				
				if(payload != null) {
					ActivityHandler handler = new ActivityHandler();
					activity = handler.parse(payload);
					initFields(activity);
				}
				
			}
			
		}
		
		return activity;
		
	}
	
	/**
	 * Create an activity with the specified name
	 * 
	 * @param activityName
	 */
	protected void createActivity(String activityName) {
		createActivity(activityName, null, null);
	}
	
	/**
	 * Create an activity with the specified name, style and data
	 * 
	 * @param activityName
	 * @param style
	 * @param publications
	 */
	protected void createActivity(String activityName, String style,
			List<DataPublicationRequest> publications) {

		ActivityResponse activity = null;

		if (!isNew) {
			activity = loadActivity(activityName);
			initFields(activity);
		} else {

			CreateActivityRequest request = CreateActivityRequest
					.createWithNameAndStyle(activityName, style, sessionHandle);
			
			for(DataPublicationRequest publication : publications) {
				request.addPublication(publication);
			}
			
			request.addMediaResourceFields(mediaResourceFields);
			request.setInitialKey(getIntent().getStringExtra(ExpanzConstants.INIT_KEY));
			
			for(String rowField : includedFields) {
				request.addField(rowField);
			}

			ExpanzCommand.getInstance().execute(request, new ServiceCallback<ActivityResponse>() {

				public void completed(ActivityResponse response) {
					// TODO Auto-generated method stub
					activityUri = response.getUri();
					initFields(response);
				}
				
			});
			
		}

	}
	
	/**
	 * Set up any field etc
	 * 
	 * @param activity
	 */
	private void initFields(ActivityResponse activity) {
		
		activityUri = activity.getUri();
		
		for(FieldResponse field : activity.getFields()) {
			
			if (fieldLabels.get(field.getId()) != null) {
				for (TextViewEx label : fieldLabels.get(field.getId())) {
					label.setText(label.isUseValue() ? field.getValue() : field
							.getLabel());
				}
			}
		
			
			List<ExpanzFieldWidget> widgets = fieldWidgets.get(field.getId());
			
			if (widgets != null) {

				for (ExpanzFieldWidget widget : widgets) {
					
					widget.setField(field);
				}

			}
			
		}
		
		for(Data data : activity.getData()) {
			
			ListViewEx listView = lists.get(data.getContextObject());
			
			if(listView != null) {
				listView.updateData(data);
			}
			
		}
		
		activityHandle = activity.getHandle();
		
		if(activity.hasMessage()) {
			displayMessages(activity.getMessages());
		}
	}
	
	

	@Override
	protected void onPause() {
		
		if(activityUri != null) {
			SharedPreferences.Editor editor = mPrefs.edit();
			editor.putString(ExpanzConstants.ACTIVITY_URI, activityUri.toString());
			editor.commit();
		}
		
		super.onPause();
	}

	
	@Override
	protected void onSaveInstanceState(Bundle outState) {
		outState.putBoolean(ExpanzConstants.NOT_NEW, true);
		super.onSaveInstanceState(outState);
	}
	
	/**
	 * Create a menu based on the process area map in the session data.
	 * 
	 * @param menuId
	 * @return
	 */
	protected void createMenu() {
		
		if(sessionHandle == null) {
			return;
		}

		GetSessionDataRequest request = new GetSessionDataRequest(sessionHandle);

		ExpanzCommand.getInstance().execute(request,
				new ServiceCallback<SessionResponse>() {

					public void completed(SessionResponse session) {

						mappings.clear();

						if (session.getMenu() == null) {
							return;
						}

					//	for (String menuItem : menuItems) {

							Map<String, ProcessAreaResponse> processAreas = session.getMenu()
									.getProcessAreas();
							
							for(Map.Entry<String, ProcessAreaResponse> entry : processAreas.entrySet()) {
								
								if (session.getMenu() != null
										&& entry.getValue() != null) {

									final List<ProcessAreaActivityResponse> activities = entry.getValue()
											.getActivities();

									for (ProcessAreaActivityResponse activity : activities) {

										ActivityMapping mapping = ActivityMappingHolder
												.getInstance().get(
														activity.getName(),
														activity.getStyle());

										if (mapping != null) {
											mapping.setTitle(activity.getTitle());
											mappings.add(mapping);
										}

									}

								}
								
							}

							

					//	}

					}

				});

	}
	
	/**
	 * Create a session for a given user
	 * 
	 * @param username
	 * @param password
	 * @return
	 */
	public void createSession(String username, String password, boolean guest, final ServiceCallback<SessionResponse> callback) {
		
		//TODO move session handle to the db and remove this convenience method from here
		
		CreateSessionRequest request = new CreateSessionRequest(username, password);
		
		if(guest) {
			request.setAuthenticationMode("guest");
		}
		
		ExpanzCommand.getInstance().execute(request, 
				new ServiceCallback<SessionResponse>() {

			public void completed(SessionResponse session) {
				
				sessionHandle = session.getSessionHandle();
				
				if(session.hasMessage()) {
					displayMessages(session.getMessages());
				}
				
				if(sessionHandle == null) {
					
					if(getParent() != null) {
						
						Intent i = new Intent();
						i.putExtra("message", "server error, check credentials/network");
						
						getParent().setResult(Activity.RESULT_CANCELED, i);
						finish();
					} 
					
				} 
				
				if(callback != null) {
					callback.completed(session);
				}
				
			}
			
		});
		
		
	}
	
	/**
	 * Recurse through the child views so they can be dynamically updated with the data from the expanz server. 
	 */
	protected void initFields() {

		if (rootLayout != null) {
			recurseChildren(rootLayout, null);
		}

	}
	
	/**
	 * Recurse each parent view and extract widgets.
	 * 
	 * @param view the parent
	 */
	private void recurseChildren(View view, String contextObject) {
		
		if(view == null) {
			return;
		}
		
		if(view instanceof ViewGroup) {
			
			int childCount = ((ViewGroup) view).getChildCount();
			
			if(childCount > 0) {
				for(int i = 0; i < childCount; i++) {
					recurseChildren(((ViewGroup) view).getChildAt(i), contextObject);
				}
			}
			
		}
		
		List<ExpanzFieldWidget> existingWidgets = null;
		
		if(view instanceof ExpanzFieldWidget) {
			ExpanzFieldWidget exView = (ExpanzFieldWidget) view;
			
			existingWidgets = fieldWidgets.get(exView.getFieldId());
			
			if(existingWidgets == null) {
				existingWidgets = new ArrayList<ExpanzFieldWidget>();
			}
		}
		
		if (view.getClass().equals(TextViewEx.class)) { //don't get subclasses
			TextViewEx label = (TextViewEx) view;
			List<TextViewEx> existingLabels = fieldLabels.get(label.getFieldId());
			
			if(existingLabels == null) {
				existingLabels = new ArrayList<TextViewEx>();
			}
			
			existingLabels.add(label);
			
			fieldLabels.put(label.getFieldId(), existingLabels);
		} else if (view instanceof ImageViewEx) {
			ExpanzFieldWidget exView = (ExpanzFieldWidget) view;
			existingWidgets.add(exView);
			fieldWidgets.put(exView.getFieldId(), existingWidgets);
			mediaResourceFields.add(exView.getFieldId());
		} else if (view instanceof ExpanzFieldWidget) {
			ExpanzFieldWidget exView = (ExpanzFieldWidget) view;
			existingWidgets.add(exView);
			fieldWidgets.put(exView.getFieldId(), existingWidgets);
		} else if (view instanceof ListViewEx) {
			ListViewEx listView = (ListViewEx) view;
			View rowView = getLayoutInflater().inflate(listView.getRowLayout(), null, true);
			lists.put(listView.getModelContextObject(), listView);
			recurseChildren(rowView, listView.getModelContextObject());
		}
		
		if(view instanceof ExpanzFieldWidget) {
			
			String fieldId = (contextObject != null) ? (contextObject + ".") : "";
			fieldId = fieldId + ((ExpanzFieldWidget)view).getFieldId();
			
			includedFields.add(fieldId);
		}
	}
	
	/**
	 * Used so we can get access to the root view so it can be recursed
	 * 
	 * @param layoutId
	 */
	protected void setRootLayout(int layoutId) {
		rootLayout = (ViewGroup) findViewById(layoutId);
		rootLayout.setFocusable(true);
		rootLayout.setFocusableInTouchMode(true);
	}
	
	/**
	 * Defines which default message handler mechanism will be used, e.g. Notifications, alerts, toasts
	 * @param messageHandlerType
	 */
	protected void setMessageHandlerType(int messageHandlerType) {
		this.messageHandlerType = messageHandlerType;
	}
	
	public void hideKeyboard() {
		
		if(rootLayout != null) {
			InputMethodManager imm = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);
			imm.hideSoftInputFromWindow(rootLayout.getWindowToken(), 0);
		}
	}
	
	/**
	 * Display a collection of messages using the default message format for the current activity 
	 */
	public void displayMessages(Collection<Message> messages) {
		for(Message message : messages) {
			displayMessage(message);
		}
	}

	/**
	 * Display a message using the default message format for the current activity 
	 */
	public void displayMessage(Message message) {
		
		if(messageHandlerType == ExpanzConstants.TYPE_NOTIFICATION) {
			NotificationManager notificationManager = (NotificationManager) getSystemService(NOTIFICATION_SERVICE);
			Notification notification = new Notification(android.R.drawable.star_on,
					"replace me", System.currentTimeMillis());
			// Hide the notification after its selected
			//notification.flags |= Notification.FLAG_AUTO_CANCEL;

			Intent intent = new Intent(this, this.getClass());
			PendingIntent activity = PendingIntent.getActivity(this, 0, intent, 0);
			notification.setLatestEventInfo(this, "replace me also",
					message.getMessage(), activity);
			notification.number += 1;
			notificationManager.notify(0, notification);
			
			
		} else if (messageHandlerType == ExpanzConstants.TYPE_TOAST) {
		    Toast.makeText(this, message.getMessage(), Toast.LENGTH_LONG).show();
		} else if (messageHandlerType == ExpanzConstants.TYPE_ALERT) {
			if(!isFinishing()) {
				new AlertDialog.Builder(this).setTitle("").setMessage(message.getMessage()).setNeutralButton("Close", null).show();
			}
		}
		
		List<ExpanzFieldWidget> widgets = fieldWidgets.get(message.getSource());

		
		if (widgets != null) {
			
			for(ExpanzFieldWidget fieldWidget : widgets) {
				
				if (fieldWidget instanceof EditTextEx) {
					
					((EditTextEx)fieldWidget).setError(message.getMessage());
				}
			}
			
		}
		
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean onPrepareOptionsMenu(Menu menu) {

		menu.clear();
		int idx = 0;
		for(ActivityMapping mapping : mappings) {
			menu.add(0, idx++, 0, mapping.getTitle());
		}

		
		return super.onPrepareOptionsMenu(menu);
		
	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean onOptionsItemSelected(MenuItem item) {
		
		ActivityMapping mapping = mappings.get(item.getItemId());
		Intent menuIntent = new Intent(this, mapping.getForm());
		menuIntent.putExtra(ExpanzConstants.SESSION_HANDLE, sessionHandle);
		startActivity(menuIntent);
		
		return super.onOptionsItemSelected(item);
	}
	
	/**
	 * hack to get around android focus button bug pre android 3.0
	 */
	public void grabFocusHack() {
		
		rootLayout.requestFocusFromTouch();
	}
	
	/**
	 * Allow child widgets to upload images.
	 */
	public void uploadImage(ImageDetails details) {
		
		imageCaptureAgent = new ImageCaptureAgent(details, activityHandle, sessionHandle, fieldWidgets, this);
		try {
			imageCaptureAgent.capture();
		} catch (IOException e) {
			displayMessage(new Message(ExpanzConstants.ERROR, e.getMessage(), null, null));
		}
	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public void onActivityResult(int requestCode, int resultCode, Intent data) {
	    super.onActivityResult(requestCode, resultCode, data);
	    switch (requestCode) {
	    case TAKE_PICTURE:
	        if (resultCode == Activity.RESULT_OK) {

				try {

					if(imageCaptureAgent != null) {
						imageCaptureAgent.send();
					}
					
				} catch (Exception e) {
					Toast.makeText(this, "Failed to upload image",
							Toast.LENGTH_SHORT).show();
					e.printStackTrace();
				}
	        }
	    }
	}


}
